# Generated by Django 4.2.8 on 2023-12-12 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectboard', '0001_initial'),
    ]

    operations = [
    ]
