# Generated by Django 4.2.8 on 2023-12-12 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectboard', '0002_rename_projectboardissue_sprintboardissue'),
    ]

    operations = [
        migrations.CreateModel(
            name='SprintBoardProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'SprintBoard Project',
                'verbose_name_plural': 'SprintBoad Projects',
            },
        ),
    ]
