# Generated by Django 4.2.8 on 2023-12-13 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectboard', '0005_rename_pub_date_sprintboardproject_creation_time_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sprintboardproject',
            old_name='name',
            new_name='title',
        ),
    ]
