# Generated by Django 4.2.8 on 2023-12-13 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projectboard', '0006_rename_name_sprintboardproject_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sprintboardissue',
            name='project_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectboard.sprintboardproject'),
        ),
    ]
